### ISSUE TITLE
OpenGL ES1.1 support

### ISSUE THREAD

**Issue by giorgosgs** [stammen/angleproject#2]
hi,

I am not very familiar with the angle project. will it work with OpenGL ES1.1 too? Is there any compartibility mode for this? thanks

**Comment by steven-chith** [comment]
In a nutshell, angle is an OpenGL ES 2.0 wrapper around a Direct3D backend. It will not work with 1.1 unfortunately. None of the fixed-function API is supported, so you'll need to rewrite any 1.1 code to the 2.0 spec. It's just due to the fact that google chrome uses it as a backend for their WebGL implementation and WebGL doesn't support fixed functionality.

**Comment by giorgosgs** [comment]
'emscripten' is an LLVM-to-JavaScript Compiler. (https://github.com/kripken/emscripten). I have used it to translate my OpenGLES 1.1 code to webGL. Normally it works with  OpenGL ES 2.0 but it has a compartibility mode for 1.1. The fact is that the webGL code generated (with minor changes) works on Chrome which uses angle in Windows. That is why I asked.

**Comment by stammen** [comment]
We are not planning ES 1.1 support at this time. You may want to take a look at the regal project:

https://github.com/p3/regal
